server:
  port: 8080
spring:
  application:
    name: "mutant-validator"
  devtools:
    add-properties: false
  jackson:
    default-property-inclusion: "NON_NULL"
  profiles:
    include: null

reactive-endpoints:
  path-base: "/api/v1"
  mutant: "/mutant"
  stats: "/stats"

adapters:
  repositories:
    tables:
      namesmap:
        mutant: MutantData

