server:
  port: 5000
spring:
  application:
    name: "mutant-validator"
  devtools:
    add-properties: false
  jackson:
    default-property-inclusion: "NON_NULL"
  profiles:
    include: null

reactive-endpoints:
  path-base: "/api/v1"
  mutant: "/mutant"
  stats: "/stats"


